// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAC-5B7W2H7tk8VPgMJS13EvHEetnNTvns',
    appId: '1:635244223861:web:77344ff4be126e7f92473c',
    messagingSenderId: '635244223861',
    projectId: 'projexa-6caed',
    authDomain: 'projexa-6caed.firebaseapp.com',
    storageBucket: 'projexa-6caed.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZ9tbJbEAnsLegw_vBpB94LX6R_9MDwws',
    appId: '1:635244223861:android:e2b2455f70ac339892473c',
    messagingSenderId: '635244223861',
    projectId: 'projexa-6caed',
    storageBucket: 'projexa-6caed.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwtgfiMCTT07YyRQw7je_3_bawHGBGnFA',
    appId: '1:635244223861:ios:6718623f5c71b07592473c',
    messagingSenderId: '635244223861',
    projectId: 'projexa-6caed',
    storageBucket: 'projexa-6caed.firebasestorage.app',
    iosBundleId: 'com.example.projexa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDwtgfiMCTT07YyRQw7je_3_bawHGBGnFA',
    appId: '1:635244223861:ios:6718623f5c71b07592473c',
    messagingSenderId: '635244223861',
    projectId: 'projexa-6caed',
    storageBucket: 'projexa-6caed.firebasestorage.app',
    iosBundleId: 'com.example.projexa',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAC-5B7W2H7tk8VPgMJS13EvHEetnNTvns',
    appId: '1:635244223861:web:5b5336e88d1e36f192473c',
    messagingSenderId: '635244223861',
    projectId: 'projexa-6caed',
    authDomain: 'projexa-6caed.firebaseapp.com',
    storageBucket: 'projexa-6caed.firebasestorage.app',
  );
}
